### PR TITLE
jsonified req.body and reply.send

### PR DESCRIPTION
**Pull request by qwelias**

### CODE REVIEW

**Comment by qwelias** [comment]
hi @Coobaha , would appreciate any feedback on it and another PR

**Comment by Coobaha** [comment]
Thank you @qwelias, I appreciate your contribution! 🙌 I will take a look soon

**Comment by qwelias** [comment]
Last commit is failing, but I couldn't figure out why.

Seems like on `test/fixtures.ts#L40` `body` is being jsonified into `{}` losing `user`, but I couldn't reproduce this in isolation, as following snippet produces correct `foo` type

```ts
interface Foo {
  asd: string
}

type foo = Jsonify<{
  foo: Foo
}>
```

**Comment by Coobaha** [comment]
I was able to get it working in #92, could you please verify? 🙏

**Pull request closed without merging**
