### PR TITLE
fix: rename definitions to properties

### PR DESCRIPTION
**Pull request by qwelias**
https://github.com/fastify/fastify-swagger/blob/master/lib/spec/swagger/utils.js#L325

### CODE REVIEW

**Comment by qwelias** [comment]
hi @Coobaha can you have a look?

**Comment by Coobaha** [comment]
@qwelias oh sorry, missed it - thanks for the ping :) will check soon!

**Comment by Coobaha** [comment]
@qwelias can you please ensure that tests are passing? 🙇

**Comment by qwelias** [comment]
yep, my bad, totally forgot about them

**Comment by qwelias** [comment]
There's still a problem with `ajv` validation I think. It does not allow `namespace` keyword in error strict mode, not sure what to do about it.

**Comment by qwelias** [comment]
@Coobaha should be good to go now

tho realistically it's a breaking change in case anyone used genereted schema

**Comment by Coobaha** [comment]
@qwelias Thanks for the contribution. Trying to understand the issue and how this PR fixes it. So when `typed-fastify` is used together with `fastify-swagger` it mutates internal json schema that is shared with fastify validations? So root issue is that something between this two plugins are incompatible or?

On the first look it seems to create new object that it mutates by deletion here https://github.com/fastify/fastify-swagger/blob/47ab4b5caca673b444932f7a45f63a1af15e4ca8/lib/spec/swagger/index.js#L22-L25

```js
    swaggerObject.definitions = prepareSwaggerDefinitions({
      ...swaggerObject.definitions,
      ...(ref.definitions().definitions)
    }, ref)
```

Please correct me if I am wrong or even better pleasee provide stackblitz example with repro.

**Comment by qwelias** [comment]
@Coobaha https://github.com/qwelias/typed-fastify-test
there's only two commits, reset between them, compare `http://127.0.0.1:3000/openapi/json` responses, click around in swagger interface

**Comment by Coobaha** [comment]
@qwelias while i understand that this fixes an issue, to me it seems that this is something that should be fixed in `https://github.com/fastify/fastify-swagger` many of json schema examples are using `definitions`, not `$defs`. Will explore more also in this plugin

**Comment by ilibar-zpt** [comment]
I believe it depends on how you `fastify.addSchema` those definitions. In your case you do just one call with whole `schemas` object instead of adding each definition separately.

I thought about fixing it by adding each definition, but it may introduce conflicts between multiple generated schemas since you can export same type names from different `.ts` files

**Comment by qwelias** [comment]
I believe it depends on how you fastify.addSchema those definitions. In your case you do just one call with whole schemas object instead of adding each definition separately.

I thought about fixing it by adding each definition, but it may introduce conflicts between multiple generated schemas since you can export same type names from different .ts files

**Comment by Coobaha** [comment]
@qwelias i've published latest version (including changes from this PR) https://www.npmjs.com/package/@coobaha/typed-fastify/v/1.0.0-rc.1

Please let me know if you will have any issues :)

**Pull request merged**
